import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { AuthProvider } from "@/hooks/use-auth";
import { Toaster } from 'sonner';
import {EdgeStoreProvider} from "@/lib/edgestore";
import { Inter } from 'next/font/google';
import React from "react";
const inter = Inter({ subsets: ['latin'], weight: ['400', '500', '600', '700'] });
export const metadata: Metadata = {
  title: "Syncora",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
          className={inter.className}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster richColors />
          <AuthProvider>
            <EdgeStoreProvider>
            {children}
            </EdgeStoreProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
